# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - LibreriaCrisolB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      # --- INICIO DE LA MODIFICACIÓN: AÑADIR ESTE PASO PARA RENOMBRAR EL WAR ---
      - name: Rename WAR to ROOT.war
        run: |
          # El artifact se descarga en el directorio de trabajo del job,
          # así que buscamos el WAR allí y lo renombramos a ROOT.war
          ls # Para depuración, para ver qué hay en el directorio de descarga
          mv $(find . -name "*.war") ROOT.war
          ls # Para depuración, para confirmar que se renombró
        working-directory: . # Asegúrate de que el comando se ejecuta donde se descargó el WAR
      # --- FIN DE LA MODIFICACIÓN ---
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EAD787AB8CF3483C9C136CC0A1A7CFCA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5EB08B33F8F40E5A1A685DC2A486B1E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E5A46740604D4BEBA3203FAC98EC23EA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LibreriaCrisolB'
          slot-name: 'Production'
          package: 'ROOT.war' # <--- MODIFICACIÓN: Ahora apunta al WAR renombrado

